### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by Yaffa16** [vishakhpk/creative-instructions#1]
Hi 
Do you plan on uploading the model on Huggingface or here soon?

**Comment by vishakhpk** [comment]
As mentioned in the Readme, here are the [model weights](https://drive.google.com/drive/folders/1mjTji9wCfX4KA039wpyQLSMx2A9jLCwe?usp=sharing) of our finetuned T5-11B model.

**Comment by Yaffa16** [comment]
Hey,the drive shows that its empty.
